Repository leam-tech/renovation-core, pull requests merged in 2020-04, with the labels that each got.

#7 Fixes+test manager update
  package.json
  src/auth/auth.controller.ts
  src/auth/frappe.auth.controller.spec.ts
  src/auth/frappe.auth.controller.ts
  src/dashboard/frappe.dashaboard.controller.spec.ts
  src/dashboard/frappe.dashboard.controller.ts
  src/defaults/frappe.defaults.controller.spec.ts
  src/defaults/frappe.defaults.controller.ts
  src/lib/frappe.spec.ts
  src/lib/frappe.ts
  src/lib/log.manager.spec.ts
  src/lib/log.manager.ts
  src/lib/message.bus.ts
  src/lib/script.manager.spec.ts
  src/lib/script.manager.ts
  src/lib/socketio.spec.ts
  src/lib/socketio.ts
  src/meta/frappe.meta.controller.spec.ts
  src/meta/frappe.meta.controller.ts
  src/meta/meta.controller.spec.ts
  src/meta/meta.controller.ts
  src/model/docfield.spec.ts
  src/model/doctype.spec.ts
  src/model/document.spec.ts
  src/model/frappe.model.controller.spec.ts
  src/model/frappe.model.controller.ts
  src/model/model.controller.spec.ts
  src/model/model.controller.ts
  src/perm/frappe.perm.controller.spec.ts
  src/perm/perm.controller.ts
  src/renovation.ts
  src/storage/file.utils.ts
  src/storage/frappe.socketiouploader.spec.ts
  src/storage/frappe.socketiouploader.ts
  src/storage/frappe.storage.controller.spec.ts
  src/storage/frappe.storage.controller.ts
  src/tests/test-manager.ts
  src/translation/frappe.translation.controller.ts
  src/translation/translation.controller.spec.ts
  src/translation/translation.controller.ts
  src/ui/ui.controller.ts
  src/utils/index.ts
  src/utils/request.ts
  src/utils/string.spec.ts
Labels: bug, enhancement

#8 chore: removed obsolete & deprecated warnings related to erpnext
  src/renovation.spec.ts
  src/renovation.ts
Labels: chore

#11 fix: import process instead of globally accessing
  src/tests/test-manager.ts
Labels: bug

#12 fix: Updated GetTags cmd
  src/model/frappe.model.controller.ts
Labels: frappe bug

#13 fix: Ability to specify reconnection attempts
  src/lib/interfaces.ts
  src/lib/socketio.ts
Labels: enhancement
